package config

EMULATOR_WINDOW_TITLE :: "Odin-8 Emulator"
MEMORY_SIZE :: 4096
PROGRAM_LOAD_ADDRESS :: 0x200
SCREEN_WIDTH :: 64
SCREEN_HEIGHT :: 32
WINDOW_SCALING :: 10

TOTAL_DATA_REGISTERS :: 16
TOTAL_STACK_DEPTH :: 16

CHARACTER_SET_LOAD_ADDRESS :: 0x00

TOTAL_KEYS :: 16
